apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/adnan-drina/coolstore-catalog-gitops.git?ref=HEAD
  creationTimestamp: null
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  name: coolstore-catalog
spec: {}
status: {}
